language: php
dist: xenial

php:
  - 7.2
  - 7.1

cache:
  directories:
    - vendor
    - $HOME/.composer

install:
  - composer self-update
  - composer install

script:
  - vendor/bin/phpunit
  - vendor/bin/phpcs src
